/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Estimacion;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author CarlosMito
 */
public class PARAMETROS_ESTIMACION_DURACION extends javax.swing.JDialog {

    public static Double strResultado = 0.0, strResultado2 = 0.0;
    public static TableModel tablaModelo;

    /**
     * Creates new form PARAMETROS_ESTIMACION_DURACION
     */
    public PARAMETROS_ESTIMACION_DURACION(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        PARAMETROS_ESTIMACION_DURACION.setDefaultLookAndFeelDecorated(true);
        jTable1.setSelectionBackground(Color.red);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jTable1.setEnabled(false);

    }

    public void verificarDatos() {


        tablaModelo = (TableModel) jTable1.getModel();

        boolean avanzar = true;

        int fila, columna;
        fila = jTable1.getSelectedRow();
        columna = jTable1.getSelectedColumn();

        if (fila == -1) {
            avanzar = false;
        } else if (columna == -1) {
            avanzar = false;
        }

        if (avanzar) {
            strResultado = Double.parseDouble(tablaModelo.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString());
            JOptionPane.showMessageDialog(null, "Dato seleccionado : " + strResultado);
            System.out.println("Dato 1 " + strResultado);
            Tabla3.tablaModelo2.setValueAt(strResultado, 0, 0);


        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un registro");
        }



    }

    public double verificarDatos2() {

//        TableModel tablaModelo; 
        tablaModelo = (TableModel) jTable1.getModel();

        boolean avanzar = true;

        int fila, columna;
        fila = jTable1.getSelectedRow();
        columna = jTable1.getSelectedColumn();

        if (fila == -1) {
            avanzar = false;
        } else if (columna == -1) {
            avanzar = false;
        }

        if (avanzar) {
            strResultado2 = Double.parseDouble(tablaModelo.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn()).toString());
            JOptionPane.showMessageDialog(null, "Dato seleccionado : " + strResultado2);
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 1);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un registro");
        }
        return strResultado2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PARAMETROS ESTIMACION DURACION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "PC", "0.503", "0.409"},
                {"2", "Multi", "0.679", "0.341"},
                {"3", "4GL", "0.578", "0.393"},
                {"4", "Nuevo", "0.739", "0.359"},
                {"5", "PC-4GL", "0.348", "0.471"},
                {"6", "Multi-4GL", "0.366", "0.451"},
                {"7", "PC-4GL-NUEVO", "0.25", "0.515"},
                {"8", "Multi-4GL-NUEVO", "0.24", "0.518"}
            },
            new String [] {
                "Nº", "Caracteristica", "C", "E"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("E");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(76, 76, 76)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        verificarDatos();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        verificarDatos2();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked


        int row = jTable1.rowAtPoint(evt.getPoint());

        int col = jTable1.columnAtPoint(evt.getPoint());
        int row2=0,row1=0,col2=0,col1=0;

        if (col == 0) {
            row2 = jTable1.rowAtPoint(evt.getPoint());

            col2 = jTable1.columnAtPoint(evt.getPoint()) + 2;
            strResultado2 = Double.parseDouble(jTable1.getValueAt(row2, col2).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 0);

            row1 = jTable1.rowAtPoint(evt.getPoint());

            col1 = jTable1.columnAtPoint(evt.getPoint()) + 3;

            strResultado2 = Double.parseDouble(jTable1.getValueAt(row1, col1).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 1, 1);
            Tabla3.tablaModelo3.setValueAt("", 2, 1);

        } else if (col == 1) {
            row2 = jTable1.rowAtPoint(evt.getPoint());
            col2 = jTable1.columnAtPoint(evt.getPoint()) + 1;
            strResultado2 = Double.parseDouble(jTable1.getValueAt(row2, col2).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 0);
            
            row1 = jTable1.rowAtPoint(evt.getPoint());

            col1 = jTable1.columnAtPoint(evt.getPoint()) + 2;

            strResultado2 = Double.parseDouble(jTable1.getValueAt(row1, col1).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 1, 1);
            Tabla3.tablaModelo3.setValueAt("", 2, 1);
        } else if (col == 2) {
             row2 = jTable1.rowAtPoint(evt.getPoint());
             col2 = jTable1.columnAtPoint(evt.getPoint());
            strResultado2 = Double.parseDouble(jTable1.getValueAt(row2, col2).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 0);
            
             row1 = jTable1.rowAtPoint(evt.getPoint());

             col1 = jTable1.columnAtPoint(evt.getPoint()) + 1;

            strResultado2 = Double.parseDouble(jTable1.getValueAt(row1, col1).toString());
            Tabla3.tablaModelo2.setValueAt(strResultado2, 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 0, 1);
            Tabla3.tablaModelo3.setValueAt("", 1, 1);
            Tabla3.tablaModelo3.setValueAt("", 2, 1);
        }

        JLabel customFontText = new JLabel();
        customFontText.setFont(new Font("Calibri", Font.BOLD, 15));
        customFontText.setText(" Los Valores Seleccionados Fueron : " + " En  'C' " + jTable1.getValueAt(row2, col2).toString()
                + " En 'E' " + jTable1.getValueAt(row1, col1).toString());
        
        JOptionPane.showMessageDialog(null, customFontText,
                "Valores", JOptionPane.INFORMATION_MESSAGE);


        dispose();

    }//GEN-LAST:event_jTable1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
